version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_smart
    hostname: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    volumes:
      - ./data/pg:/var/lib/postgresql/data

  library:
    container_name: library_smart
    hostname: library
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8005:8005'
    environment:
        POSTGRES_MIG_PATH: "file://../library/cmd/migrations"
    restart: always