version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_smart
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    volumes:
      - ./data:/var/lib/postgresql/data

#  library:
#    restart: always
#    image:
#    container_name: library_smart
#    ports: